# Generated by Django 3.1.6 on 2021-02-17 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0002_remove_person_last_name'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RemoveField(
                    model_name='person',
                    name='last_name',
                ),
            ]
        )
    ]
